[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    jgromes/RadioLib @ ^6.0.0
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
monitor_speed = 115200
